bug #105 Move symfony/error-handler to non-dev dependencies (acrobat)
This PR was squashed before being merged into the 1.x branch.

Discussion
----------

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | 
| License       | MIT

After I've updated to  v1.2.0-BETA1 I got this error. The install/upgrade scripts do a composer install without dev depencies which causes this dependency to not be available.

```
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\ErrorHandler\ErrorHandler" not found in /Users/xxxx/.hubkit/bin/hubkit.php:23
Stack trace:
#0 {main}
  thrown in /Users/xxxx/.hubkit/bin/hubkit.php on line 23

Fatal error: Uncaught Error: Class "Symfony\Component\ErrorHandler\ErrorHandler" not found in /Users/xxxx/.hubkit/bin/hubkit.php on line 23

Error: Class "Symfony\Component\ErrorHandler\ErrorHandler" not found in /Users/xxxx/.hubkit/bin/hubkit.php on line 23
```

Commits
-------

48735cd9b6cc9083cd041dfb98775a89ab98d329 Move symfony/error-handler to non-dev dependencies
110487324e4ec50db95a797a350f09ab3b821070 Update phpstan baseline with updated error message